import type { NextPage } from 'next'
import Head from 'next/head'
import { useWallet } from 'use-wallet'
import { Toaster } from 'react-hot-toast'

import { ENSSection, TxStatesSection, GMModeSection, WalletConnectSection } from '../components/web3FeatureSections'
import AdminPanel from '../components/adminPanel'
import Navbar from '../components/navbar'

const Home: NextPage = () => {
  const wallet = useWallet()
  const { status } = wallet

  return (
    <div className="max-w-screen-xl m-auto">
      <Head>
        <title>Web 3 Starter Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toaster />
      <Navbar />

      <h1 className="m-auto text-center md:mt-8 text-4xl md:text-6xl font-extrabold">
        Welcome to <span className="rotating-hue">Web 3 Starter</span>
      </h1>

      <div className="flex flex-col space-y-4 justify-center mt-6 md:mt-12 px-4 xs:px-0 m-auto max-w-4xl">
        <WalletConnectSection />
        <ENSSection />
        <TxStatesSection />
        <GMModeSection />
      </div>

      <div className="flex justify-center mt-8">
        {status === 'connected' && (
          <div className="flex space-x-3">
            <AdminPanel />
            <AdminPanel />
          </div>
        )}
      </div>
      <style jsx>{`
        .rotating-hue {
          background-image: -webkit-linear-gradient(92deg, #f35626, #feab3a);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          -webkit-animation: hue 30s infinite linear;
        }

        @-webkit-keyframes hue {
          from {
            -webkit-filter: hue-rotate(0deg);
          }
          to {
            -webkit-filter: hue-rotate(-360deg);
          }
        }
      `}</style>
    </div>
  )
}

export default Home
